kind = "mobile"
previewPath = "/"
title = "Zombie Survival"
version = "1.0.0"
id = "artifacts/zombie-game"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 25476

[services.development]
run = "pnpm --filter @workspace/zombie-game run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/zombie-game", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/zombie-game", "run", "serve" ]

[services.env]
PORT = "25476"
BASE_PATH = "/"
